# Generated by Django 5.0.3 on 2024-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rezerwacje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stolik',
            name='nakrycie',
        ),
        migrations.AddField(
            model_name='stolik',
            name='dzien',
            field=models.CharField(choices=[('PONIEDZIALEK', 'poniedzialek'), ('WTOREK', 'wtorek'), ('SRODA', 'sroda'), ('CZWARTEK', 'czwartek'), ('PIATEK', 'piatek'), ('SOBOTA', 'sobota'), ('NIEDZIELA', 'niedziela')], default='SOBOTA', max_length=16),
        ),
        migrations.AddField(
            model_name='stolik',
            name='godzina',
            field=models.CharField(choices=[('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], default='20:00', max_length=16),
        ),
    ]
