# Generated by Django 5.0.3 on 2024-04-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rezerwacje', '0003_alter_stolik_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stolik',
            options={'verbose_name_plural': 'Stoliki'},
        ),
    ]
