# Generated by Django 5.0.3 on 2024-04-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rezerwacje', '0004_alter_stolik_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'verbose_name_plural': 'Rezerwacje'},
        ),
    ]
